import {Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const cairo = Cairo({
  display : 'swap',
  subsets: ['latin'],
});

export const metadata = {
  title: "Bakar Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cairo.className} antialiased`}
      >
        <nav>
           <Navbar/>
        </nav>
        {children}
      </body>
    </html>
  );
}
